//
// Created by notoraptor on 15/09/2019.
//

#ifndef GUIRAPTOR_DRAWINGTYPE_HPP
#define GUIRAPTOR_DRAWINGTYPE_HPP

enum DrawingType {
	DRAWING_TYPE_IMAGE,
	DRAWING_TYPE_TEXT,
	DRAWING_TYPE_RECTANGLE,
	DRAWING_TYPE_CIRCLE,
	DRAWING_TYPE_REGULAR_POLYGON,
	DRAWING_TYPE_POLYGON,
	DRAWING_TYPE_ELLIPSE,
	DRAWING_TYPE_SURFACE,
	NB_DRAWING_TYPE
};

#endif //GUIRAPTOR_DRAWINGTYPE_HPP
